### ISSUE TITLE
Remove links to source maps

### ISSUE THREAD

**Issue by mattes3** [tasoskakour/react-use-oauth2#10]
Thanks for this fantastic library!

When using it in my React app, Webpack complains about non-existent source maps. Can you please remove them so that Webpack doesn't try to find them anymore?

Here is the error message:

```
WARNING in ../../node_modules/@tasoskakour/react-use-oauth2/dist/esm/index.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/.../node_modules/@tasoskakour/react-use-oauth2/src/src/components/use-oauth2.ts' file: Error: ENOENT: no such file or directory, open '/Users/.../node_modules/@tasoskakour/react-use-oauth2/src/src/components/use-oauth2.ts'
```

**Comment by tasoskakour** [comment]
Hello @mattes3, glad you're finding it useful!

I'm afraid I cannot replicate the error you're describing. 

Could you provide a sandbox please?

**Comment by adilkaraoz** [comment]
Here is example app to reproduce this error
[my-app.zip](https://github.com/tasoskakour/react-use-oauth2/files/10855244/my-app.zip)

**Comment by tasoskakour** [comment]
Hello @mattes3! 

You can use the newest version -> `1.1.0` of the package which does not include source maps.

Cheers :wave:
