### ISSUE TITLE
How to "Logout" and remove the persisted data

### ISSUE THREAD

**Issue by JTson8** [tasoskakour/react-use-oauth2#4]
Hello, 
I have everything working great so thank you for that!
One functionality that I have not figured out yet is how to logout and to basically set the persisted data to null.
Is there anyway to do this?
 
Thank you!

**Comment by JTson8** [comment]
nvm.
Simply doing
`localStorage.removeItem({responseType}-{authorizeUrl}-{clientId}-{scope})`
did the trick.

**Comment by tasoskakour** [comment]
Hey @JTson8! 

That's a nice feature to have. I'll add it in the backlog :-)
