### ISSUE TITLE
Custom query params in exchangeCodeForTokenServerURL

### ISSUE THREAD

**Issue by AniketHQ** [tasoskakour/react-use-oauth2#63]
So, basically after user authorization, the frontend makes call to the backend with just 5 query params `{ code, client_id, grant_type, redirect_uri, state }` but in some cases, oauth providers attach extra params to the url which are getting lost while a call is being made to `exchangeCodeForTokenServerURL`.

We should have the functionality to pass all the params along with the above ones to the backend server.

**Comment by tasoskakour** [comment]
Hey @AniketHQ, can you post please an example demonstrating what you want to achieve and with which provider?
