### ISSUE TITLE
Integration with Python Authlib

### ISSUE THREAD

**Issue by zach-iwx** [tasoskakour/react-use-oauth2#8]
Hello,

I am currently trying to build a React application using this library and I seem to hit a wall. I am trying to use the Authorization Code grant type to log in via a popular LMS (LearnUpon). Using the sample code provided in this repository, I configured the useOauth2 hook using the below settings:

```
const { data, loading, error, getAuth } = useOAuth2({
    authorizeUrl: "https://{{redacted}}.learnupon.com/oauth/authorize",
    clientId: "{{redacted}}",
    redirectUri: `https://{{redacted}}.ngrok.io/callback`,
    scope: "full offline_access",
    responseType: "code",
    exchangeCodeForTokenServerURL: "http://localhost:9000/auth",
    exchangeCodeForTokenMethod: "GET",
    onSuccess: (payload) => console.log("Success", payload),
    onError: (error_) => console.log("Error", error_)
  });
```

I am exposing the React application in dev mode using [ngrok](https://ngrok.com/). The OAuth popup screen comes up successfully, however the response I get back from my API via Authlib when attempting issue the access token is as follows:

```
{
    "detail": "mismatching_state: CSRF Warning! State not equal in request and response."
}
```

Why is the state query parameter not sent to my /auth endpoint? Also another curious thing is that my /auth endpoint is raising an HTTP exception which is originating from the Authlib StarletteOAuth2App client. Although in the React UI, it is being logged to the console as a successful login attempt.

Am I doing something ridiculously wrong here? Any information would be helpful.

**Comment by tasoskakour** [comment]
Hello @zach-iwx 

I modified the code so that the state parameter is also sent to the `exchangeCodeForTokenServerURL` endpoint as a query parameter.
Fixed on version `1.0.13`.

Could you try again and let me know?
