### ISSUE TITLE
Not working with react 17 (or below)

### ISSUE THREAD

**Issue by flipersclub** [tasoskakour/react-use-oauth2#85]
I am encountering the error "You are using React 17 or below. Install with "npm install use-local-storage-state@17"

This can't be corrected using the instruction as the module requires the use-local-storage-state@18 which itself requires react@18. This has been since version 1.0.10.

**Comment by tasoskakour** [comment]
Hey @flipersclub thanks for your highlighting this issue.

Indeed it looks like the `use-local-strage-state` package that this library uses does not support react < 18. 

We've got two options: 

1. Require users of this library to have a React version at least `>=18`
2. Implement our own `useLocalStorageState` hook and drop the dependency of the `use-local-storage-state` library.
3. Put `use-local-storage-state` in peerDependencies and let the user of this library install the 3rd party library independently. 

At the moment I'm opting to go with option 1. Obviously, option 2 is the most ideal.

As far as option 3 goes, I think that it would be a bit of an "overkill" right now to require users of this library to install 3rd party packages themselves.

Of course if we realize that the need for `react<=17` is getting higher, then we're going to revisit this :)
