### ISSUE TITLE
Backend token URL called twice

### ISSUE THREAD

**Issue by kalirajan-natarajan** [tasoskakour/react-use-oauth2#90]
This plug in is really good. With out a lot of difficulties, I was able to get this used for my project. 

However I encountered a small issue.

I have been using this for an OAuth2 flow that is not a login. However the concepts remain the same. 
After the login / authorisation has been completed in the popup, the backend token URL is getting called twice. 

I have changed the token URL to be a GET as well as POST. 

Any updates on this would be highly appreciated

**Comment by dzz828** [comment]
I got same issue in my nextjs app which has react strict mode enabled by default - but when I turn it off the issue is not there any more…

**Comment by joey-kwl** [comment]
Read this for more information about double fetching: https://react.dev/reference/react/useEffect#my-effect-runs-twice-when-the-component-mounts

**Comment by tasoskakour** [comment]
This issue is now fixed in `v1.4.0` :tada: 

Related PR: https://github.com/tasoskakour/react-use-oauth2/pull/96
