### ISSUE TITLE
audience: add query parameter

### ISSUE THREAD

**Issue by tetra12** [tasoskakour/react-use-oauth2#98]
oauth2 `audience` must be requested. Currently, `aud` is not requested and not returned. My example:
```sh
{
  "aud": [], <-------- must NOT be empty

  "client_id": "dafc3613-93cc-487f-8b53-acf56c258c87",
  "exp": 1705277961,
  "ext": {},
  "iat": 1705234760,
  "iss": "http://192.168.1.93:4444",
  "jti": "89dff623-1adb-4c21-8a7a-ee165feed06b",
  "nbf": 1705234760,
  "scp": [
    "openid",
    "offline",
    "email"
  ],
  "sub": "aed89977-dea1-4e30-a2df-63635fc46d64"
}
```
My request:
```ts
const { data, loading, error, getAuth, logout } = useOAuth2({
    authorizeUrl: import.meta.env.VITE_AUTH_URL,
    clientId: import.meta.env.VITE_CLIENT_ID,
    redirectUri: import.meta.env.VITE_REDIRECT_URI,
    scope: "openid offline email ec2",
    responseType: "code",

    extraQueryParameters: { audience: "MyCorp" }, //<------ Requested `audience`. No success


    exchangeCodeForTokenServerURL: import.meta.env.VITE_TOKEN_BACK_URL,
    exchangeCodeForTokenMethod: "POST",
    onSuccess: (payload: TAuthTokenPayload) => console.log("Success:", payload),
    onError: (error_) => console.log("Error", error_),
  });
```
UPD: 
Tested the following: 
1. `extraQueryParameters: { audience: ["Foo"] },` <--- Works
2. `extraQueryParameters: { audience: ["Foo", "Bar"] },` <--- Fails
`error: message:invalid_request reason:Requested audience 'Foo,Bar' is not found in the OAuth 2.0 Client. stack_trace`

This happens since `extraQueryParameters` merges array into a single string, whereas `audience` requires an input array

**Comment by tasoskakour** [comment]
Hello @tetra12 :wave: 

The query parameters are serialized using the standard function: `URLSearchParams(object).toString()` as seen [here](https://github.com/tasoskakour/react-use-oauth2/blob/2c5a748c44cdcf75c0f3d9422ce8d96747c0e733/src/components/tools.ts#L5) 

The reason that your `audience: ["Foo", "Bar"]` is convered to a string is because you pass it as an array. 

But if you pass it as a string already then it's array structure will be retained, e.g: 

```
const { data, loading, error, getAuth, logout } = useOAuth2({
   ....
    extraQueryParameters: { audience: "["Foo","Bar"]" }, // <------ Notice the surrounding " " 
    ...
  });
```
